language: cpp
sudo: required
dist: trusty
services:
  - docker
compiler:
  - gcc
  - clang
git:
  submodules: false
before_install:
  - docker build -t slack-gtk .
before_script:
  - docker run slack-gtk $CXX --version
script:
  - docker run -e CXX=$CXX slack-gtk ../ci/build.sh
matrix:
  allow_failures:
    - compiler: clang
